id: PFA067517
initial_creation_type: input
source_metadata:
  title: Mañjuśrī Series
  language: es
  description: 'Texts related to Mañjuśrī (''jam dpal) or Mañjughoṣa (''jam pa''i
    dbyangs), the Buddha or Bodhisattva of Wisdom:'
  volume:
    d004df1d49dc432bbf63214ae81b2a08:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Ārya Mañjuśrī Tantra Citta
    6d80d3c09a104e1683b570a10cedaaa0:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Ārya Mañjuśrī Tantra Citta
    7f2f6e7f174a42c18a98f72d85c0495e:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Chanting the Names of Mañjuśrī
    f9f099db005b4341b456279f81e9e675:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    259f3c98b99f4f1589d02d2bbcd3a695:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    5977be1ce2c4418994a20b43152bf038:
      title: 'The Healing Medicine of Faith: A Prayer to the Lineage of the Peaceful
        Sādhana of Mañjuśrī'
      parent: Lineage Prayers
    d3c68bbb99804198b87fad46c90cad37:
      title: The Meaning of the Six Syllables of the King of Vidyā-Mantras, the Heroic
        Lord Mañjuśrī
      parent: Mantra
    b9b9df2c8d284d91957ce54f93172cd2:
      title: 'The Fresh Saffron Flower: In Praise of Venerable Mañjughoṣa'
      parent: Praise
    2a01f1ed751847c59a27c1a6804f642c:
      title: 'The Light of Wisdom: Praise to Mañjuśrī'
      parent: Praise
    e58df66042a043298e535cde57aa1f24:
      title: 'The Lute of Vajra Harmony: Praise to the Protector Mañjuśrī'
      parent: Praise
    df2850af571744bf922df15e76c38aab:
      title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
      parent: Praise
    729f5851ec9147d78f01ed5435b8c205:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Praise
    f7509726c527426eb75e6e1015ed40b2:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Praise
    ec264839e3f84bfeb4861d05ce5f7cd9:
      title: In Praise of the Protector Mañjughoṣa
      parent: Praise
    eb9125ad719b4831aa224738e45cfa4d:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      parent: Praise
    3c99fc47a3964d0f8ab5d65936237403:
      title: Praise to Mañjughoṣa
      parent: Praise
    4b7763e0cd1447199b76154c8dd19014:
      title: 'A Few Remarks: An Explanation of the Praise to Noble Mañjuśrī known
        as Glorious Wisdom’s Excellent Qualities'
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    90ac0c57dd8846c9af62773145ecba72:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    8338d32ee2d34944a7d85807641d552e:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
    04360fe2bab940c4a035878890b26e01:
      title: A Prayer to Mañjuśrī
      parent: Prayers
    e556293af4d24ac1a748548bfb6fb065:
      title: Prayer to Bhagavān Mañjughoṣa
      parent: Prayers
    90c58fde2b0d4fbfaf959c31fde146cd:
      title: Prayer to the Lion of Speech
      parent: Prayers
    0649c9bb42404fb69851cfd074ef5c00:
      title: Prayer to Mañjuśrī
      parent: Prayers
    2163c2c3bc6c4e1d8bbcb07178bcbd0c:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    be0e35c6f58a407ab0e5262a421e0eb9:
      title: 'The Torch of Wisdom: A Method of Offering Butter Lamps Based on Ārya
        Mañjuśrī'
      parent: Rituals
    bd54d100955c41949570dbdf9ab4c67f:
      title: Light from the Wisdom Sun
      parent: Sādhanas
    6740204285de40af9fd7a87223bf4de3:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Sādhanas
    f638654e2af84d929840f97f45db53b9:
      title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
      parent: Sādhanas
    605c55cd87ee43d7be1b74e8197728c9:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    09abdb0a9c2f42d5a19bca1d263c6c88:
      title: Sādhana of Mañjughoṣa
      parent: Sādhanas
created_at: '2022-03-01T04:36:26.578533'
last_modified_at: '2022-03-01T04:36:26.578537'
